/** @type {import('knip').KnipConfig} */
const config = {
  entry: [
    'projects/dashboard/src/main.ts!',
    'projects/dashboard/src/app/app.config.ts!',
    'projects/dashboard/src/app/app.routes.ts!',
    'projects/dashboard/src/environments/environment*.ts!',
  ],
  project: ['projects/dashboard/src/**/*.{ts,html,scss}'],
  ignore: [
    '**/*.spec.ts',
    '**/*.stories.ts',
    '**/docs/**',
    '**/.worktrees/**',
    '**/storybook-static/**',
  ],
  ignoreDependencies: [
    // Invoked via npm scripts / Angular builders, not direct imports.
    '@angular-devkit/build-angular',
    '@angular/build',
    '@angular/cli',
    '@angular/compiler-cli',
    '@compodoc/compodoc',
    '@playwright/test',
    '@storybook/addon-a11y',
    '@storybook/addon-docs',
    '@storybook/angular',
    '@storybook/test-runner',
    'angular-eslint',
    'concurrently',
    'http-server',
    'jsdom',
    'prettier',
    'storybook',
    'typescript',
    'vitest',
    'wait-on',
    'eslint',
    'typescript-eslint',
    '@eslint/js',
    'eslint-plugin-sonarjs',
    'stylelint',
    'stylelint-config-standard',
    'stylelint-config-standard-scss',
    'jscpd',
    'knip',
    'dependency-cruiser',
  ],
  ignoreBinaries: ['ng'],
};

module.exports = config;
