"""HTTP-backed service adapters used by the Linux installer."""

from .base import (
    AdapterPlan,
    AdapterResult,
    Checkpoint,
    Drift,
    ServiceCheckpoint,
    ServiceDrift,
    ServicePlan,
    ServiceResult,
)
from .jellyfin import (
    JellyfinAdapter,
    JellyfinAuthenticationError,
    JellyfinAuthError,
    JellyfinApiKeyHandoff,
    JellyfinApiKeySchemaError,
    JellyfinCapability,
    JellyfinCapabilityError,
    JellyfinError,
    JellyfinResult,
    JellyfinSchemaError,
    JellyfinSession,
    JellyfinSessionError,
    configure_jellyfin,
    plan_jellyfin,
)

__all__ = [
    "AdapterPlan",
    "AdapterResult",
    "Checkpoint",
    "Drift",
    "JellyfinAdapter",
    "JellyfinAuthenticationError",
    "JellyfinAuthError",
    "JellyfinApiKeyHandoff",
    "JellyfinApiKeySchemaError",
    "JellyfinCapability",
    "JellyfinCapabilityError",
    "JellyfinError",
    "JellyfinResult",
    "JellyfinSchemaError",
    "JellyfinSession",
    "JellyfinSessionError",
    "ServiceCheckpoint",
    "ServiceDrift",
    "ServicePlan",
    "ServiceResult",
    "configure_jellyfin",
    "plan_jellyfin",
]
