"""Linux installer command package for Lumen Media Hub."""

from .errors import (
    DriftError,
    ExitCode,
    InstallerError,
    InvalidInputError,
    NotAvailableError,
    PartialError,
)
from .answers import Answers, Resolver
from .dotenv import DotEnvDocument, write_atomic
from .environment import EnvironmentChange, EnvironmentPlan, plan_environment
from .platform import HostFacts, detect_host
from .secrets import ensure_actions_token
from .network import (
    JELLYFIN_BIND_ADDRESS,
    JELLYFIN_REMOTE_ACCESS,
    LAN_BIND_ADDRESS,
    LOCAL_BIND_ADDRESS,
    LOCAL_PUBLIC_HOST,
    MANAGEMENT_BIND_ADDRESS,
    PUBLIC_HOST,
    NetworkPlan,
    plan_network,
)
from .commands import (
    DEFAULT_TIMEOUT,
    CommandExecutor,
    CommandError,
    CommandExecutionError,
    CommandResult,
    CommandRunner,
    normalize_stream,
)
from .docker import (
    COMPOSE_MINIMUM,
    DependencyPlan,
    DecisionRecord,
    DockerPreflight,
    ManifestInspection,
    PlannedCommand,
    PreflightError,
    UnsupportedDistroError,
    UnsupportedPlatformError,
    dependency_plan,
    docker_preflight,
    inspect_manifest_architectures,
    parse_compose_version,
    parse_docker_version,
    run_host_doctor,
    validate_compose_version,
)
from .state import (
    DEFAULT_STAGES,
    InstallerState,
    KNOWN_GPU_MODES,
    KNOWN_PROFILES,
    STATE_DIR_NAME,
    STATE_FILE_NAME,
    STATE_LOCK_NAME,
    StageJournal,
    state_directory,
    state_path,
)
from .storage import (
    DOWNLOAD_SUBDIRECTORIES,
    KNOWN_STACK_CONTAINER_NAMES,
    MEDIA_SUBDIRECTORIES,
    STORAGE_DIRECTORY_MODE,
    StaleContainer,
    StorageMutationError,
    StorageValidation,
    find_stale_containers,
    validate_storage,
)

__all__ = [
    "DriftError",
    "ExitCode",
    "InstallerError",
    "InvalidInputError",
    "NotAvailableError",
    "PartialError",
    "Answers",
    "DotEnvDocument",
    "EnvironmentChange",
    "EnvironmentPlan",
    "HostFacts",
    "Resolver",
    "detect_host",
    "ensure_actions_token",
    "JELLYFIN_BIND_ADDRESS",
    "JELLYFIN_REMOTE_ACCESS",
    "LAN_BIND_ADDRESS",
    "LOCAL_BIND_ADDRESS",
    "LOCAL_PUBLIC_HOST",
    "MANAGEMENT_BIND_ADDRESS",
    "NetworkPlan",
    "PUBLIC_HOST",
    "plan_network",
    "plan_environment",
    "write_atomic",
    "CommandError",
    "CommandExecutionError",
    "CommandExecutor",
    "CommandResult",
    "CommandRunner",
    "DEFAULT_TIMEOUT",
    "COMPOSE_MINIMUM",
    "DependencyPlan",
    "DecisionRecord",
    "DockerPreflight",
    "ManifestInspection",
    "PlannedCommand",
    "PreflightError",
    "UnsupportedDistroError",
    "UnsupportedPlatformError",
    "dependency_plan",
    "docker_preflight",
    "inspect_manifest_architectures",
    "parse_compose_version",
    "parse_docker_version",
    "run_host_doctor",
    "validate_compose_version",
    "normalize_stream",
    "DEFAULT_STAGES",
    "InstallerState",
    "KNOWN_GPU_MODES",
    "KNOWN_PROFILES",
    "STATE_DIR_NAME",
    "STATE_FILE_NAME",
    "STATE_LOCK_NAME",
    "StageJournal",
    "state_directory",
    "state_path",
    "DOWNLOAD_SUBDIRECTORIES",
    "KNOWN_STACK_CONTAINER_NAMES",
    "MEDIA_SUBDIRECTORIES",
    "STORAGE_DIRECTORY_MODE",
    "StaleContainer",
    "StorageMutationError",
    "StorageValidation",
    "find_stale_containers",
    "validate_storage",
]
