import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { LucideCircleCheck, LucideInfo, LucideAlertCircle, LucideLoaderCircle } from '@lucide/angular';

@Component({ selector: 'mm-button', standalone: true, imports: [LucideLoaderCircle], changeDetection: ChangeDetectionStrategy.OnPush, template: `<button [type]="type()" [disabled]="disabled()" [attr.aria-busy]="busy() || null" [class]="'mm-button mm-button--' + variant()">@if (busy()) { <svg lucideLoaderCircle [size]="16" [strokeWidth]="2.2" aria-hidden="true"></svg> }{{ label() }}</button>`, styles: `:host { display: inline-block; } .mm-button { display: inline-flex; align-items: center; gap: 8px; border: 0; border-radius: var(--mm-radius-sm); padding: 10px 14px; background: var(--mm-component-accent); color: var(--mm-component-on-accent); cursor: pointer; font: 700 13px/1 var(--mm-font-body); } .mm-button--quiet { background: var(--mm-component-control-bg); color: var(--mm-component-text-primary); } .mm-button:disabled { cursor: wait; opacity: .65; }` })
export class MmButton { readonly label = input('Continue'); readonly variant = input<'primary' | 'quiet'>('primary'); readonly disabled = input(false); readonly busy = input(false); readonly type = input<'button' | 'submit'>('button'); }

@Component({ selector: 'mm-status', standalone: true, imports: [LucideCircleCheck, LucideInfo, LucideAlertCircle], changeDetection: ChangeDetectionStrategy.OnPush, template: `<span [class]="'mm-status mm-status--' + tone()">@if (tone() === 'success') { <svg lucideCircleCheck [size]="15" aria-hidden="true"></svg> } @else if (tone() === 'danger') { <svg lucideAlertCircle [size]="15" aria-hidden="true"></svg> } @else { <svg lucideInfo [size]="15" aria-hidden="true"></svg> }<span><ng-content /></span></span>`, styles: `.mm-status { display: inline-flex; align-items: center; gap: 7px; border-radius: 999px; padding: 6px 10px; background: var(--mm-component-muted-bg); color: var(--mm-component-text-secondary); font: 700 12px/1 var(--mm-font-body); } .mm-status--success { color: var(--mm-component-success); } .mm-status--warning { color: var(--mm-component-warning); } .mm-status--danger { color: var(--mm-component-danger); } .mm-status--info { color: var(--mm-component-accent); }` })
export class MmStatus { readonly tone = input<'success' | 'warning' | 'danger' | 'info'>('info'); }

@Component({ selector: 'mm-progress', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<div class="mm-progress" role="progressbar" [attr.aria-label]="label()" [attr.aria-valuenow]="value()" aria-valuemin="0" aria-valuemax="100"><div class="mm-progress__bar" [style.width.%]="value()"></div></div><span class="mm-progress__label">{{ value() }}%</span>`, styles: `.mm-progress { height: 8px; overflow: hidden; flex: 1; border-radius: 999px; background: var(--mm-component-border); } .mm-progress__bar { height: 100%; border-radius: inherit; background: var(--mm-component-accent); transition: width .2s ease; } .mm-progress__label { min-width: 38px; color: var(--mm-component-text-secondary); font-size: 12px; text-align: right; }` })
export class MmProgress { readonly value = input(0); readonly label = input('Progress'); }

@Component({ selector: 'mm-poster', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<article class="mm-poster"><div class="mm-poster__art" [style.background]="art()"><span>{{ title() }}</span></div><div class="mm-poster__body"><strong>{{ title() }}</strong><small>{{ meta() }}</small></div></article>`, styles: `.mm-poster { width: 180px; overflow: hidden; border: 1px solid var(--mm-component-border); border-radius: var(--mm-radius-md); background: var(--mm-component-card-bg); box-shadow: var(--mm-shadow-card); } .mm-poster__art { aspect-ratio: 2 / 3; display: flex; align-items: end; padding: 14px; color: var(--mm-component-on-accent); font-size: 20px; font-weight: 800; letter-spacing: -.03em; } .mm-poster__body { display: grid; gap: 5px; padding: 12px; } .mm-poster__body strong { color: var(--mm-component-text-primary); font-size: 13px; } .mm-poster__body small { color: var(--mm-component-text-muted); }` })
export class MmPoster { readonly title = input('Moonrise'); readonly meta = input('2026 · Drama'); readonly art = input('linear-gradient(145deg, var(--mm-component-accent), var(--mm-component-card-bg) 65%)'); }

@Component({ selector: 'mm-state-card', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="mm-state-card" [class]="'mm-state-card mm-state-card--' + tone()"><div class="mm-state-card__icon" aria-hidden="true">{{ icon() }}</div><h3>{{ title() }}</h3><p>{{ message() }}</p><ng-content /></section>`, styles: `.mm-state-card { display: grid; justify-items: start; gap: 8px; padding: 22px; border: 1px dashed var(--mm-component-border); border-radius: var(--mm-radius-md); background: var(--mm-component-card-bg); } .mm-state-card__icon { display: grid; place-items: center; width: 34px; height: 34px; border-radius: 50%; background: var(--mm-component-muted-bg); color: var(--mm-component-accent); font-size: 17px; } .mm-state-card--danger .mm-state-card__icon { color: var(--mm-component-danger); } h3, p { margin: 0; } h3 { color: var(--mm-component-text-primary); font-size: 15px; } p { color: var(--mm-component-text-secondary); font-size: 13px; line-height: 1.5; }` })
export class MmStateCard { readonly icon = input('◌'); readonly title = input('Nothing here yet'); readonly message = input('There is no content to show right now.'); readonly tone = input<'default' | 'danger'>('default'); }
